name: Fastapi CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.10']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'    
    # Step-2 Install Python Virtual ENV
    - name: Install Python Virtual ENV
      run: pip3 install virtualenv

    # Step-3 Setup Virtual ENV
    # https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows
    - name:  Virtual ENV
      uses: actions/cache@v2
      id: cache-venv # name for referring later
      with:
        path: venv # what we cache: the Virtual ENV
        # The cache key depends on requirements.txt
        key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-venv-
    # Step-4 Build a Virtual ENV, but only if it doesn't already exist
    - name: Activate Virtual ENV
      run: python -m venv venv && source venv/bin/activate && pip3 install -r requirements.txt
      if: steps.cache-venv.outputs.cache-hit != 'true'

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8
    # - name: Run Tests
    #   run: |
    #     python manage.py test